### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by llucenic** [dlang-tour/core#506] opened 2017-04-27 09:43 UTC
Hi, I would like to help translating D-Tour into Slovak language.

**Comment by ZombineDev** [comment] 2017-04-28 17:53
Hi @llucenic, thanks for your interest in contributing. I'll setup repo soon.

**Comment by ZombineDev** [comment] 2017-04-29 17:34
@llucenic I've just setup a [repo](https://github.com/dlang-tour/slovak) and sent you an invitation to join the [Slovak](https://github.com/orgs/dlang-tour/teams/slovak) translation team. Let me know if you need more information on how to get started.

**Comment by llucenic** [comment] 2017-05-19 14:04
Hi Petar, thank you for setting up the repo for me. I would like to know two more things regarding the translation process:
* how do I properly translate the comments in the source code snippets? The source code shown in the CodeMirror on the generated translated page does not seem to reflect translations, or any changes in general, to the code.
* how do I translate 'Run' button? Is it possible to do so within the dlang-tour/slovak source or does this have to be done somehow in primary project?

Thank you very much for any hints.

**Comment by ZombineDev** [comment] 2017-05-19 15:06
Hi Ľudovít!

> how do I properly translate the comments in the source code snippets? The source code shown in the CodeMirror on the generated translated page does not seem to reflect translations, or any changes in general, to the code.

I'm not sure if I properly understand your problem, but the content repos at github.com/dlang-tour/ contain everything - both the explanations and the code, including comments. I'm not sure why you aren't seeing changes to the code. As you can see [here](https://tour.dlang.org/tour/en/welcome/languages), most of the non-English translation haven't still incorporated the hello world code example that was recently changed in the English version.

> how do I translate 'Run' button? Is it possible to do so within the dlang-tour/slovak source or does this have to be done somehow in primary project?

Currently translating the text in UI elements is not possible, though we want to implement it. The plan is to use the `index.yml` files in language repo for this, though I can't make any promises regarding when, but PRs are always welcome ;)

For further information, you can check the [wiki](https://github.com/stonemaster/dlang-tour/wiki/Tips-for-translators).

**Comment by wilzbach** [comment] 2017-05-19 15:11
> Currently translating the text in UI elements is not possible, though we want to implement it. The plan is to use the index.yml files in language repo for this, though I can't make any promises regarding when,

@llucenic

This will be possible starting from this weekend (I will make a PR tomorrow and ping you with the instructions), but as @ZombineDev mentioned it will be just another entry in the main index.yml file

**Comment by llucenic** [comment] 2017-05-19 15:33
Hi guys, thank you for hints. I am looking forward to the PR.

The problem I see is that after translating the [welcome page](https://github.com/dlang-tour/slovak/blob/llucenic/welcome/welcome-to-d.md) I see this in my localhost dlang-tour:

![obrazok](https://cloud.githubusercontent.com/assets/2933634/26255092/df5b4efc-3cb8-11e7-8c27-703f05bdb53f.png)

As you can see I have changed the code snippet (a string and the comments), but these changes were not applied.

**Comment by ZombineDev** [comment] 2017-05-19 17:35
That's quite strange. Here's what I get with your branch: 
![dlang-tour-slovak](https://cloud.githubusercontent.com/assets/3475150/26259526/14c2d812-3cd2-11e7-809b-7fc6b7f3b0ec.png)

Perhaps there's some sort of browser caching going on here, can you try forcing the browser to clear its cache?

**Comment by wilzbach** [comment] 2017-05-19 18:31
> I will make a PR tomorrow and ping you with the instructions)

-> https://github.com/stonemaster/dlang-tour/pull/510

> That's quite strange. Here's what I get with your branch:

@llucenic How build your translation? With `dub run dlang tour -- --lang-dir .`?
As "Ahoj svet" is written on the right side, it really seems like a cache issue with your browser. Be sure to do sth. like:

![image](https://cloud.githubusercontent.com/assets/4370550/26261622/2e1e2a46-3cd2-11e7-8d6a-81735f129966.png)

**Comment by llucenic** [comment] 2017-05-19 18:55
Thank you guys for your assistance. The string "Ahoj svet!" was my own edit, I have forgotten it in the meanwhile that I had played a bit with the code in the editor. **The only thing that helped me was the Reset button** above the code editor. Once you edit the snippet, there is no other way the editor would reload the original content. No cache disabling, browser refresh, cache flushing etc. However, **problem solved.**

**Comment by wilzbach** [comment] 2017-05-19 19:05
"It's not a bug, it's a feature"

![image](https://cloud.githubusercontent.com/assets/4370550/26262904/c12012e2-3cd6-11e7-95ea-94183044e3f7.png)

To be fair, saving a user's edits for permanently (for some time), is usually a useful feature ;-)

**Comment by llucenic** [comment] 2017-05-19 19:56
No problem :-) Just the user should know...

**Comment by wilzbach** [comment] 2017-07-01 21:15
@llucenic I am closing this now as the slovak repo (https://github.com/dlang-tour/slovak) is since quite a while deployed online:

https://tour.dlang.org/tour/sk

Please don't hesitate to open a new issue if you run into troubles.
Lastly, don't forgot to add Slovak to the [translated languages](https://tour.dlang.org/tour/en/welcome/languages) once the first page is translated ;-)

**Closed by wilzbach** 2017-07-01 21:15 UTC
